const ERR_NODE_NOT_FOUND = 'ERR_NODE_NOT_FOUND'
const ERR_KEY_NOT_FOUND = 'ERR_KEY_NOT_FOUND'
const ERR_EXTREMITY_NOT_FOUND = 'ERR_EXTREMITY_NOT_FOUND'

export {
  ERR_KEY_NOT_FOUND, ERR_NODE_NOT_FOUND, ERR_EXTREMITY_NOT_FOUND
}
